insert into public.casestudies
    values
    (DEFAULT, 
        'QuantumNet Protocol', 
        'Quantum Computing', 
        'Revolutionary quantum communication protocol achieving 99.9% fidelity across global networks.',
        'Developed a groundbreaking quantum communication protocol that enables secure, instantaneous data transmission across global networks with unprecedented fidelity rates. This breakthrough addresses the fundamental challenges of quantum decoherence and signal degradation over long distances.',
        '10x faster quantum communication', 
        'Deployed Globally', 
        '18 months', 
        '12 specialists', 
        'Global Tech Consortium', 
        'https://images.pexels.com/photos/8919549/pexels-photo-8919549.jpeg?auto=compress&cs=tinysrgb&w=800',
        array['Quantum','Networking','Security','Global Infrastructure'], 
        array['99.9% communication fidelity achieved','10x improvement in transmission speed','Zero security breaches in 12 months','Deployed across 50+ global nodes'],
        array['Quantum Entanglement','Error Correction','Photonic Networks','Cryptographic Protocols']
    ),
    (DEFAULT, 
        'FusionCore Reactor', 
        'Energy Systems', 
        'Next-generation compact fusion reactor with unprecedented energy efficiency.',
        'Engineered a revolutionary compact fusion reactor design that achieves sustained fusion reactions in a significantly smaller footprint, making clean fusion energy commercially viable for the first time.',
        '500MW clean energy output', 
        'Prototype Testing', 
        '36 months', 
        '25 specialists', 
        'Energy Innovation Consortium', 
        'https://images.pexels.com/photos/1476321/pexels-photo-1476321.jpeg?auto=compress&cs=tinysrgb&w=800',
        array['Fusion','Clean Energy','Innovation','Sustainability'], 
        array['500MW sustained energy output','95% energy conversion efficiency','Zero carbon emissions','80% smaller reactor footprint'],
        array['Magnetic Confinement','Plasma Physics','Superconducting Magnets','Advanced Materials']
    ),
    (DEFAULT, 
        'BioSynth Engine', 
        'Biotechnology', 
        'AI-powered synthetic biology platform for rapid drug discovery and development.',
        'Created an advanced AI-driven platform that accelerates drug discovery through synthetic biology, reducing development timelines from years to months while maintaining safety and efficacy standards.',
        '75% reduction in discovery time', 
        'Clinical Trials', 
        '24 months', 
        '18 specialists', 
        'Pharmaceutical Alliance', 
        'https://images.pexels.com/photos/5726794/pexels-photo-5726794.jpeg?auto=compress&cs=tinysrgb&w=800',
        array['AI','Biotechnology','Drug Discovery','Machine Learning'], 
        array['75% faster drug discovery process','90% accuracy in compound prediction','15 compounds in clinical trials','$500M in development cost savings'],
        array['Machine Learning','Protein Folding','Molecular Simulation','Biomarker Analysis']
    ),
    (DEFAULT, 
        'NanoHeal Materials', 
        'Materials Science', 
        'Self-healing nanomaterials for aerospace and medical applications.',
        'Developed breakthrough self-healing nanomaterials that can autonomously repair damage, extending lifespan and reducing maintenance requirements across critical applications.',
        '90% maintenance reduction', 
        'Production Ready', 
        '20 months', 
        '14 specialists', 
        'Aerospace Defense Corp', 
        'https://images.pexels.com/photos/8439093/pexels-photo-8439093.jpeg?auto=compress&cs=tinysrgb&w=800',
        array['Nanotechnology','Materials','Aerospace','Self-Healing'], 
        array['90% reduction in maintenance needs','300% increase in material lifespan','Certified for aerospace applications','Patent portfolio of 25+ innovations'],
        array['Nanoengineering','Smart Polymers','Molecular Assembly','Surface Chemistry']
    ),
    (DEFAULT, 
        'CarbonCapture Matrix', 
        'Climate Solutions', 
        'Advanced atmospheric carbon capture and conversion system.',
        'Engineered a revolutionary atmospheric carbon capture system that not only removes CO2 from the air but converts it into valuable industrial materials, creating a profitable carbon-negative process.',
        '1M tons CO2 captured annually', 
        'Pilot Deployment', 
        '30 months', 
        '20 specialists', 
        'Climate Action Alliance', 
        'https://images.pexels.com/photos/9324336/pexels-photo-9324336.jpeg?auto=compress&cs=tinysrgb&w=800',
        array['Climate','Carbon Capture','Sustainability','Environmental'], 
        array['1M tons CO2 captured per year','95% conversion efficiency','Revenue-positive operations','Scalable to global deployment'],
        array['Direct Air Capture','Catalytic Conversion','Process Optimization','Industrial Integration']
    ),
    (DEFAULT, 
        'NeuroLink Interface', 
        'Neurotechnology', 
        'Non-invasive brain-computer interface for medical rehabilitation.',
        'Created a breakthrough non-invasive brain-computer interface that enables direct neural control of external devices, revolutionizing rehabilitation for patients with mobility impairments.',
        '85% mobility restoration', 
        'FDA Review', 
        '28 months', 
        '16 specialists', 
        'Medical Research Institute', 
        'https://images.pexels.com/photos/8439093/pexels-photo-8439093.jpeg?auto=compress&cs=tinysrgb&w=800',
        array['Neurotechnology','Medical','Rehabilitation','Brain-Computer Interface'], 
        array['85% mobility function restoration','99.7% signal accuracy','Non-invasive implementation','500+ successful patient trials'],
        array['Neural Signal Processing','Machine Learning','Biocompatible Materials','Real-time Computing']
    ),
    (DEFAULT, 
        'HyperSpeed Logistics', 
        'Transportation', 
        'Autonomous hyperloop transportation system for cargo delivery.',
        'Developed a fully autonomous hyperloop system optimized for high-speed cargo transport, reducing delivery times and transportation costs while maintaining zero emissions.',
        '10x faster cargo delivery', 
        'Commercial Testing', 
        '42 months', 
        '30 specialists', 
        'Global Logistics Network', 
        'https://images.pexels.com/photos/1592384/pexels-photo-1592384.jpeg?auto=compress&cs=tinysrgb&w=800',
        array['Transportation','Automation','Logistics','Hyperloop'], 
        array['10x faster delivery speeds','70% cost reduction','Zero emissions transport','99.9% delivery accuracy'],
        array['Magnetic Levitation','Vacuum Systems','Autonomous Control','Route Optimization']
    ),
    (DEFAULT, 
        'AquaPure System', 
        'Water Technology', 
        'Advanced water purification using quantum filtration technology.',
        'Engineered a quantum-enhanced water purification system that removes all contaminants while preserving beneficial minerals, providing clean water access in any environment.',
        '99.99% purification efficiency', 
        'Global Deployment', 
        '22 months', 
        '12 specialists', 
        'Water Access Foundation', 
        'https://images.pexels.com/photos/1292241/pexels-photo-1292241.jpeg?auto=compress&cs=tinysrgb&w=800',
        array['Water Technology','Quantum Filtration','Environmental','Global Health'], 
        array['99.99% contaminant removal','50M people served','90% energy efficiency','Deployed in 30+ countries'],
        array['Quantum Filtration','Membrane Technology','IoT Monitoring','Solar Integration']
    );

insert into public.stats
    values
    (DEFAULT,'Patents Pending','10+'),
    (DEFAULT,'Market Impact','$18M+'),
    (DEFAULT,'Lives Improved','220K'),
    (DEFAULT,'Success Rate','98%'),
    (DEFAULT,'Work in Progress PhD','1'),
    (DEFAULT,'Case Studies','30+'),
    (DEFAULT,'Years Combined Experience','100+'),
    (DEFAULT,'Innovations Delivered','100+'),
    (DEFAULT,'Whiteboards','10+'),
    (DEFAULT,'Operations','24/7');

insert into public.people
    values
    (DEFAULT,
        'Anthony J. Mauceri', 
        'Role', 
        'Specialty', 
        'https://media.licdn.com/dms/image/v2/D4E03AQEvYDgJbPAAYw/profile-displayphoto-shrink_200_200/B4EZSltnBTG0AY-/0/1737946985368?e=1759363200&v=beta&t=DvZJISpaMG8QGUSi_CskBBur8XyxRswuee4LrHr-G2s', 
        array['MIT PhD','Nature Publications','Quantum Pioneer Award'], 
        'Proclaimed Technowizard.',
        'https://www.linkedin.com/in/anthony-j-mauceri/'
    ),
    (DEFAULT,
        'Sebastian Dytrych', 
        'Role', 
        'Specialty', 
        'https://cdn.discordapp.com/attachments/1401381257488760876/1409675941256364154/IMG20250825190702.jpg?ex=68bd67c6&is=68bc1646&hm=bed16550eb32148957e95f94f0cb3469a1efb1f7c014ad7f9a8220201798510f&', 
        array['Harvard PhD','200+ Patents','Biotech Innovator Award'], 
        'Very special.',
        'https://www.linkedin.com/in/sebastian-dytrych-47801726b/'
    ),
    (DEFAULT,
        'Ryan Piedrahita', 
        'Role', 
        'Specialty', 
        'https://media.licdn.com/dms/image/v2/C4E03AQHhGQoZK7FdXw/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1653531427831?e=1759363200&v=beta&t=os568ikuWJvxsgZByC2kj-kVRDamkzaUxE21g5hsB40', 
        array['Caltech PhD','Fusion Breakthrough','Energy Innovation Prize'], 
        'Employed.',
        'https://www.linkedin.com/in/rpiedev/'
    ),
    (DEFAULT,
        'Vin deAugustino', 
        'Board Member', 
        'Specialty', 
        'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=400', 
        array['MIT PhD','Nature Publications','Quantum Pioneer Award'], 
        'Description.',
        ''
    ),
    (DEFAULT,
        'Victor Lawrence', 
        'Board Member', 
        'Specialty', 
        'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=400', 
        array['MIT PhD','Nature Publications','Quantum Pioneer Award'], 
        'Description.',
        ''
    ),
    (DEFAULT,
        'Will McLoid', 
        'Board Member', 
        'Specialty', 
        'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=400', 
        array['MIT PhD','Nature Publications','Quantum Pioneer Award'], 
        'Description.',
        ''
    );